name: 'Argo Gke Deploy'
description: 'Update version in a ApplicationSet in argo'

inputs:
  external_token:
    description: 'External token'
    required: true
    default: 'nopath'
  yaml_path:
    description: 'Path to file to patch'
    required: true
    default: 'nopath'
  version_path:
    description: 'In the file, path to version section'
    required: true
    default: ''
  version:
    description: 'version'
    required: true
    default: ''
  gke_deploy_repo_name:
    description: 'gke_deploy_repo_name'
    required: true
    default: ''

runs:
  using: "composite" # Indica que es una combinación de pasos
  steps:
    - name: Dar permisos al script
      shell: bash
      # 'github.action_path' es la ruta donde vive tu action, no el repo del usuario
      run: chmod +x ${{ github.action_path }}/script.sh

    - id: script
      name: Deploy version
      shell: bash
      run: ${{ github.action_path }}/script.sh
      env:
        # Se crean variables de entorno que el script puede leer
        EXTERNAL_TOKEN: ${{ inputs.external_token }}
        YAML_PATH: ${{ inputs.yaml_path }}
        VERSION_PATH: ${{ inputs.version_path }}
        VERSION: ${{ inputs.version }}
        REPO_NAME: ${{ inputs.gke_deploy_repo_name }}